In [1]:
import pandas as pd

ratings = pd.read_csv('C:/Users/karpo/Desktop/Презентации аналитика/python/ml-latest-small/ml-latest-small/ratings.csv')
movie = pd.read_csv('C:/Users/karpo/Desktop/Презентации аналитика/python/ml-latest-small/ml-latest-small/movies.csv')
joined = ratings.merge(movie, on='movieId', how='left')

In [2]:
lifetime = joined.groupby('userId').agg([min, max])
lifetime.head()

       movieId         rating        timestamp              \
           min     max    min  max         min         max
userId
1            1    5060    1.0  5.0   964980499   965719662
2          318  131724    2.0  5.0  1445714835  1445715340
3           31   72378    0.5  5.0  1306463323  1306464293
4           21    4967    1.0  5.0   945078428  1007574542
5            1     608    1.0  5.0   847434747   847435337

                                    title                              \
                                      min                         max
userId
1                13th Warrior, The (1999)       ¡Three Amigos! (1986)
2                       Collateral (2004)           Zombieland (2009)
3                             2012 (2009)      You've Got Mail (1998)
4                     12 Angry Men (1957)          Wonder Boys (2000)
5       Ace Ventura: Pet Detective (1994)  Usual Suspects, The (1995)

                               genres
                                  min          max
userId
1                    Action|Adventure     Thriller
2         Action|Adventure|Crime|IMAX  Sci-Fi|IMAX
3                              Action       Sci-Fi
4                    Action|Adventure      Western
5       Action|Adventure|Comedy|Crime     Thriller

In [3]:
joined['deff'] = (lifetime['timestamp']['max'] - lifetime['timestamp']['min']) / 86400
joined.head()

,userId,movieId,rating,timestamp,title,genres,deff
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,NaN
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance,8.555127
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller,0.005845
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,0.011227
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,723.334653

In [5]:
clik = joined.groupby('userId').count()
clik100 = clik[(clik['rating'] >=100)]
clik100.head(100)

        movieId  rating  timestamp  title  genres  deff
userId
1           232     232        232    232     232   231
4           216     216        216    216     216   216
6           314     314        314    314     314    51
7           152     152        152    152     152     0
10          140     140        140    140     140     0
15          135     135        135    135     135     0
17          105     105        105    105     105     0
18          502     502        502    502     502     0
19          703     703        703    703     703     0
20          242     242        242    242     242     0
21          443     443        443    443     443     0
22          119     119        119    119     119     0
23          121     121        121    121     121     0
24          110     110        110    110     110     0
27          135     135        135    135     135     0
28          570     570        570    570     570     0
32          102     102        102    102     102     0
33          156     156        156    156     156     0
39          100     100        100    100     100     0
40          103     103        103    103     103     0
41          217     217        217    217     217     0
42          440     440        440    440     440     0
43          114     114        114    114     114     0
45          399     399        399    399     399     0
47          140     140        140    140     140     0
50          310     310        310    310     310     0
51          359     359        359    359     359     0
52          130     130        130    130     130     0
57          476     476        476    476     476     0
58          112     112        112    112     112     0
...         ...     ...        ...    ...     ...   ...
166         190     190        190    190     190     0
167         173     173        173    173     173     0
169         269     269        269    269     269     0
177         904     904        904    904     904     0
181         118     118        118    118     118     0
182         977     977        977    977     977     0
184         134     134        134    134     134     0
186         226     226        226    226     226     0
187         258     258        258    258     258     0
195         187     187        187    187     187     0
198         230     230        230    230     230     0
199         363     363        363    363     363     0
200         334     334        334    334     334     0
201         110     110        110    110     110     0
202         403     403        403    403     403     0
210         138     138        138    138     138     0
212         248     248        248    248     248     0
216         164     164        164    164     164     0
217         613     613        613    613     613     0
219         528     528        528    528     528     0
220         207     207        207    207     207     0
221         331     331        331    331     331     0
222         250     250        250    250     250     0
226         507     507        507    507     507     0
230         139     139        139    139     139     0
232         862     862        862    862     862     0
233         150     150        150    150     150     0
234         202     202        202    202     202     0
239         279     279        279    279     279     0
240         128     128        128    128     128     0

[100 rows x 6 columns]