In [1]:
import pandas as pd
from datetime import datetime
from datetime import timedelta

ratings = pd.read_csv('C:/Users/karpo/Desktop/Презентации аналитика/python/ml-latest-small/ml-latest-small/ratings.csv')
movie = pd.read_csv('C:/Users/karpo/Desktop/Презентации аналитика/python/ml-latest-small/ml-latest-small/movies.csv')
joined = ratings.merge(movie, on='movieId', how='left')

In [2]:
years = []
start_year, end_year = '1950', '2018'

start_year_d = datetime.strptime(start_year, '%Y')
end_year_d = datetime.strptime(end_year, '%Y')

while start_year_d <= end_year_d:
    years.append(start_year_d.strftime('%Y'))
    
    start_year_d += timedelta(days = 365)

In [3]:
def production_year (row):
    for year in years:
        if year in row['title']:
            return (year)
    return '1900'

In [5]:
joined ['year'] = joined.apply(production_year, axis = 1)

In [6]:
joined.groupby('year').mean().sort_values('rating', ascending=False)

          userId        movieId    rating     timestamp
year
1957  315.865116    3012.213953  4.039535  1.178092e+09
1954  315.735294    2426.022059  4.009191  1.159430e+09
1962  328.343511    4645.015267  3.969466  1.145154e+09
1952  356.708333    2687.718750  3.953125  1.156213e+09
1972  321.437500    4742.921196  3.944293  1.182165e+09
1964  321.351064    4900.795213  3.940160  1.180442e+09
1974  319.420601    3556.620172  3.935622  1.172035e+09
1967  312.167979    4951.223097  3.922572  1.162747e+09
1975  329.667190    3207.897959  3.879121  1.167952e+09
1958  341.042424    3267.648485  3.842424  1.114448e+09
1971  335.555347    4727.836773  3.841463  1.155517e+09
1966  339.021053   11602.578947  3.823684  1.205284e+09
1950  325.291925    4402.739130  3.813665  1.166512e+09
1968  323.290323    5358.142857  3.812212  1.160851e+09
1977  330.654321    4906.860670  3.810406  1.176425e+09
1951  331.719780    2104.802198  3.804945  1.136664e+09
1959  334.958848    2709.139918  3.794239  1.141051e+09
1900  336.743741   13937.295042  3.792096  1.180579e+09
1981  332.231061    3959.550505  3.760732  1.149468e+09
1976  346.574468    4141.723404  3.760047  1.154248e+09
1973  335.830228    6417.192547  3.757764  1.155729e+09
1970  327.000000    5543.331967  3.754098  1.114961e+09
1965  310.384615    8878.311966  3.735043  1.167439e+09
1980  337.012712    3303.977754  3.733581  1.162009e+09
1960  337.948207    3800.266932  3.721116  1.163617e+09
1955  353.615385    3942.093407  3.719780  1.136474e+09
1961  323.911111    6044.808889  3.700000  1.161863e+09
1969  318.684932    7114.954338  3.682648  1.105720e+09
1956  394.295652    4670.304348  3.682609  1.142896e+09
1979  329.038168    4568.357506  3.676845  1.163923e+09
...          ...            ...       ...           ...
2007  318.374892   55492.220449  3.522433  1.355426e+09
2014  327.444697  114790.476515  3.512879  1.473975e+09
2012  336.643372   96362.609510  3.512608  1.451164e+09
1982  339.273504    2887.172840  3.510921  1.149102e+09
2004  329.681711   13285.484956  3.507227  1.296885e+09
1994  308.467145     766.327228  3.500944  1.055582e+09
2006  335.717215   48309.502901  3.499033  1.327894e+09
1999  329.608466    3422.948854  3.498677  1.172115e+09
1987  346.993506    3922.337013  3.488312  1.153141e+09
2001  328.774259    5401.997957  3.482125  1.247649e+09
1989  332.134565    2780.721900  3.463061  1.142196e+09
2003  325.034340    8729.750397  3.462321  1.280538e+09
2011  338.663889   89407.326389  3.460764  1.437914e+09
1986  346.763441    3417.012018  3.460152  1.138101e+09
2013  336.216847  105494.064220  3.457048  1.465729e+09
1978  353.653061    5832.489796  3.455102  1.152125e+09
1993  319.644213    1474.743919  3.452152  1.075248e+09
1995  311.229818     429.228678  3.443848  1.049419e+09
1985  345.528698    3726.748585  3.434115  1.153617e+09
1990  326.232087    3154.670301  3.427310  1.129963e+09
1998  322.911161    2720.859994  3.427186  1.167948e+09
1988  341.358065    4129.747742  3.419032  1.155216e+09
2002  325.882175    6493.643505  3.414584  1.250048e+09
2015  325.107537  132983.079044  3.410386  1.483150e+09
2000  321.353947    4632.339424  3.398922  1.211202e+09
2016  320.759236  151577.561783  3.387261  1.502460e+09
2005  333.066506   37330.044471  3.359976  1.309928e+09
1992  323.776728    3429.598707  3.353555  1.133193e+09
1997  320.920670    2470.630524  3.347241  1.153470e+09
1996  313.544688    1273.748281  3.335329  1.067905e+09

[69 rows x 4 columns]

In [7]:
joined.head()

,userId,movieId,rating,timestamp,title,genres,year
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance,1995
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller,1995
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995